### ISSUE TITLE
Would it be possible to make this exclude channel pages?

### ISSUE THREAD

**Issue by googleooer** [garygcchiu/YouTube-Recommendations-Filter#2]
I want the uBlock filters to hide mixes and already watched videos in the homescreen, but I want to see all the videos when scrolling through a channel's uploaded videos.

**Comment by garygcchiu** [comment]
With the way these Adblock filters work, these rules cannot be selectively applied to specific subpages only, it's either applied to the entire domain or not at all.

**Comment by garygcchiu** [comment]
@googleooer I've found a workaround for this. Instead of using this rule:

```
www.youtube.com##ytd-thumbnail-overlay-resume-playback-renderer:upward(ytd-rich-item-renderer)
```

Try this (basically adding the :not() filter):

```
www.youtube.com##ytd-thumbnail-overlay-resume-playback-renderer:upward(ytd-rich-item-renderer:not([is-slim-grid=""]))
```

It's not supported by all Adblock engines (needs to support CSS selectors), but works on uBlock Origin for me.
